"""add GPS coordinates to plots and projects

Revision ID: 3751547b776a
Revises: 3d5230ab9d4e
Create Date: 2026-07-22 12:03:29.815647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3751547b776a'
down_revision: Union[str, None] = '3d5230ab9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
