"""add support tickets, payment orders, commission payouts, richer plot fields

Revision ID: 3aa3c6729e9f
Revises: b20524ea94d3
Create Date: 2026-07-07 16:18:06.155611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3aa3c6729e9f'
down_revision: Union[str, None] = 'b20524ea94d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('plots', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plots', sa.Column('amenities', sa.Text(), nullable=True))
    op.add_column('plots', sa.Column('patta_number', sa.String(length=100), nullable=True))
    op.add_column('plots', sa.Column('google_maps_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'google_maps_link')
    op.drop_column('plots', 'patta_number')
    op.drop_column('plots', 'amenities')
    op.drop_column('plots', 'description')
    op.drop_column('plots', 'image_url')
    # ### end Alembic commands ###
