"""add GPS coordinates to plots and projects

Revision ID: 3d5230ab9d4e
Revises: e47e8eb560b2
Create Date: 2026-07-22 10:49:20.355771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d5230ab9d4e'
down_revision: Union[str, None] = 'e47e8eb560b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_payouts',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_payouts_tenant_id'), 'commission_payouts', ['tenant_id'], unique=False)
    op.add_column('plots', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('plots', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    op.drop_column('plots', 'longitude')
    op.drop_column('plots', 'latitude')
    op.drop_index(op.f('ix_commission_payouts_tenant_id'), table_name='commission_payouts')
    op.drop_table('commission_payouts')
    # ### end Alembic commands ###
