"""add is_active to user response

Revision ID: 78d4d12f5552
Revises: 3aa3c6729e9f
Create Date: 2026-07-07 17:12:30.926920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78d4d12f5552'
down_revision: Union[str, None] = '3aa3c6729e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
