"""add subscription start date and platform payment orders

Revision ID: c873e2eb9e09
Revises: 25a6e5528606
Create Date: 2026-07-22 18:16:51.343675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c873e2eb9e09'
down_revision: Union[str, None] = '25a6e5528606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_payment_orders',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_key', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'FAILED', name='platformorderstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.add_column('tenants', sa.Column('subscription_started_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_started_at')
    op.drop_table('platform_payment_orders')
    # ### end Alembic commands ###
