"""add unique constraint preventing double-booking a plot

Revision ID: e47e8eb560b2
Revises: 78d4d12f5552
Create Date: 2026-07-07 17:19:49.675858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e47e8eb560b2'
down_revision: Union[str, None] = '78d4d12f5552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_active_booking_per_plot', 'bookings', ['plot_id'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_active_booking_per_plot', table_name='bookings', postgresql_where=sa.text("status != 'cancelled'"))
    # ### end Alembic commands ###
