"""add tenant expiry/history, plot DTCP-RERA fields

Revision ID: e70aeb9ef7b5
Revises: 3751547b776a
Create Date: 2026-07-22 16:34:31.288250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e70aeb9ef7b5'
down_revision: Union[str, None] = '3751547b776a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_plan_history',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('old_plan', sa.String(length=20), nullable=True),
    sa.Column('new_plan', sa.String(length=20), nullable=True),
    sa.Column('old_expires_at', sa.Date(), nullable=True),
    sa.Column('new_expires_at', sa.Date(), nullable=True),
    sa.Column('changed_by_email', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plots', sa.Column('dtcp_approved', sa.Boolean(), nullable=True))
    op.add_column('plots', sa.Column('dtcp_number', sa.String(length=100), nullable=True))
    op.add_column('plots', sa.Column('rera_approved', sa.Boolean(), nullable=True))
    op.add_column('plots', sa.Column('rera_number', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('subscription_expires_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_expires_at')
    op.drop_column('plots', 'rera_number')
    op.drop_column('plots', 'rera_approved')
    op.drop_column('plots', 'dtcp_number')
    op.drop_column('plots', 'dtcp_approved')
    op.drop_table('tenant_plan_history')
    # ### end Alembic commands ###
